version: 2.1

parameters:
  cache-generation:
    type: integer
    default: 2

orbs:
  win: circleci/windows@5.0

jobs:
  test-linux:
    parameters:
      python-version:
        type: string

    docker:
      - image: python:<< parameters.python-version >>

    steps:
      - checkout

      - run: &save-python-version
          name: Save full python version in file to be used as part of cache key
          command: python -V > /tmp/python-V.txt

      - restore_cache: &restore-cache-env
          key: &env-cache-key v<< pipeline.parameters.cache-generation >>-python-{{ checksum "/tmp/python-V.txt" }}-pip-{{ checksum "pyproject.toml" }}-{{ .Environment.CIRCLE_JOB }}

      - run: &create-venv-install-deps
          name: Create virtual environment and install dependencies
          command: |
            python -m venv env
            . env/bin/activate
            pip install -U pip setuptools wheel twine build
            pip install --group dev --group test

      - save_cache: &save-cache-env
          key: *env-cache-key
          paths:
            - env

      - run: &run-tests
          name: Run unit tests
          command: |
            . env/bin/activate
            coverage run -m pytest

      - run: &run-codecov
          name: Run codecov
          command: |
            . env/bin/activate
            codecov

  test-macos:
    parameters:
      python-version:
        type: string
      xcode:
        type: string
        default: "16.4.0"

    macos:
      xcode: << parameters.xcode >>

    steps:
      - checkout

      - restore_cache: &restore-cache-pyenv
          key: &brew-pyenv-cache-key v<< pipeline.parameters.cache-generation >>-brew-pyenv-{{ .Environment.CIRCLE_JOB }}-xcode-<< parameters.xcode >>

      - run: &brew-install-pyenv
          name: Install pyenv
          command: |
            brew update
            brew install pyenv

      - run: &pyenv-install-python
          name: Install python
          command: pyenv install << parameters.python-version >> -s

      - run: &pyenv-set-system-python
          name: Set system python
          command: |
            echo -e '\n\n# Initialize pyenv' >> ~/.bash_profile
            echo 'eval "$(pyenv init --path 2>/dev/null || true)"' >> ~/.bash_profile
            echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
            pyenv global << parameters.python-version >>

      - save_cache: &save-cache-pyenv
          key: *brew-pyenv-cache-key
          paths:
            - /Users/distiller/Library/Caches/Homebrew
            - /usr/local/Homebrew
            - ~/.pyenv

      - run: *save-python-version

      - restore_cache: *restore-cache-env

      - run: *create-venv-install-deps

      - save_cache: *save-cache-env

      - run: *run-tests

      - run: *run-codecov

  test-windows:
    parameters:
      python-version:
        type: string

    executor:
      name: win/default

    steps:
      - checkout

      - run:
          name: Install python and create virtualenv
          shell: bash -eo pipefail
          command: |
            # de-normalize a pre-release version, because why would microsoft follow pep-440?
            version=$(sed -E 's/([[:digit:]])([[:alpha:]])/\1-\2/' \<<<"<< parameters.python-version >>")

            # resolve python MAJOR.MINOR[.PATCH[-PRERELEASE]] version to the latest
            # MAJOR.MINOR.PATCH version available on NuGet (ignoring the actual pre-release segment)
            # note: we rely on versions retrieved being sorted semantically!
            # (so '3.13' might resolve to '3.13.0rc3' before final release, and to '3.13.0' afterwards)
            full_version=$(
              curl -s 'https://azuresearch-usnc.nuget.org/query?q=python&prerelease=true' \
              | jq -r '.data[] | select(.id == "python") .versions[] | .version' \
              | awk -F'[.-]' -v ver="$version" \
                  'index($0, ver) == 1 && $3 >= m { m = $3; v = $0 } END { print v }'
            )

            nuget install python -Version "$full_version" -ExcludeVersion
            python/tools/python -V
            python/tools/python -m venv env

      - run:
          name: Install dependencies
          command: |
            env\Scripts\activate.ps1
            python --version
            python -m pip install -U pip setuptools wheel twine
            pip install --group dev --group test

      - run:
          name: Run unit tests
          command: |
            env\Scripts\activate.ps1
            coverage run -m pytest

  deploy:
    docker:
      - image: python:3.12

    steps:
      - checkout

      - run: *create-venv-install-deps

      - run:
          name: Verify version matches tag
          command: |
            . env/bin/activate
            pip install .
            [[ "$(pip show dwave-qiskit-plugin 2>/dev/null | grep Version)" == "Version: $CIRCLE_TAG" ]]

      - run:
          name: Build package
          command: |
            . env/bin/activate
            python -m build

      - run:
          name: Upload to PyPI
          command: |
            . env/bin/activate
            twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --skip-existing ./dist/*

workflows:
  test:
    jobs:
      - test-linux:
          matrix:
            parameters:
              python-version: &python-versions ["3.11", "3.12", "3.13", "3.14"]
      - test-macos:
          matrix:
            parameters:
              python-version: *python-versions
      - test-windows:
          matrix:
            parameters:
              python-version: *python-versions

  deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*((\.dev|rc)([0-9]+)?)?$/
            branches:
              ignore: /.*/
